name: notifyservice

include:
  - path: ./docker-compose.infra.yml
  - path: ./docker-compose.observability.yml
  - path: ./docker-compose.app.yml

networks:
  notifyservice_network:
    driver: bridge

