services:
  # Linux host requirement:
  # sudo sysctl -w vm.max_map_count=262144

  # PostgreSQL Database
  postgres:
    image: postgres:17.9-alpine3.23
    container_name: notifyservice_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ${POSTGRES_DB:-NotifyService_Dev}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - notifyservice_network

  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:4.2.5-management-alpine
    container_name: notifyservice_rabbitmq
    command: /bin/sh -c "rabbitmq-plugins enable --offline rabbitmq_prometheus && rabbitmq-server"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI
      - "15692:15692" # Prometheus metrics
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - notifyservice_network

volumes:
  postgres_data:
    driver: local
  rabbitmq_data:
    driver: local
