apiVersion: 1

prune: true

datasources:
  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    editable: false
    jsonData:
      derivedFields:
        - name: trace_id
          matcherRegex: "(?:trace_id|TraceId)=([A-Fa-f0-9]{32})"
          datasourceUid: tempo
          url: '$${__value.raw}'
          urlDisplayLabel: View Trace

  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: false

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    editable: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: 'loki' 
        tags: ['service.name']
        filterByTraceID: true
        spanStartTimeShift: '-5m'
        spanEndTimeShift: '5m'
      serviceMap:
        datasourceUid: 'prometheus'
      nodeGraph:
        enabled: true
